version: 2
jobs:   
  test_build:
    docker:
      - image: circleci/ruby:2.3.4
    steps:
      - checkout
      - run: 
          name: bundle install
          command: bundle install
      - run:
          name: test jekyll build
          command: bundle exec jekyll build
          timeout: 2400
  deployment:
    docker:
      - image: circleci/ruby:2.3.4
    working_directory: ~/devportal
    steps:
      - checkout
      - run:
          name: chmod it
          command: chown -R $USER:$USER /home/circleci/project
      - run:
          name: bundle install
          command: bundle install
      - run:
          name: algolia push
          command: bundle exec jekyll algolia push
          timeout: 2400
      - run:
          name: set git email
          command: git config --global user.email 'greg+cedevportal@cloud-elements.com'
      - run:
          name: set git username
          command: git config --global user.name 'cedevportal'
      - run:
          name: deploy it 
          command: cd _site; git init && git remote add gh "https://${GITHUB_USERNAME}:${GITHUB_PASSWORD}@github.com/cloud-elements/cloud-elements.github.io.git" && git add -A && git commit -m 'Live release' && git push gh master --force

workflows:
  version: 2
  premerge:
    jobs:
      - test_build:
          filters:
            branches:
              ignore: master
      - manual_deploy_approve:
          type: approval
      - deploy:
          requires:
            - manual_deploy_approve
  master_oncommit:
    jobs:
      - deployment:
          filters:
            branches:
              only:
                - master
